name: Vercel Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_EXPERIMENTAL_STANDALONE_BUILD: 1

on:
  push:
    branches-ignore:
      - main

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vc build --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_EXPERIMENTAL_STANDALONE_BUILD: ${{ env.VERCEL_EXPERIMENTAL_STANDALONE_BUILD }}

      - name: Move all .vercel folders to output
        run: |
          mkdir -p output
          find . -type d -name ".vercel" -exec bash -c 'dir="{}"; cp -r "$dir"/* output/' \;

      - name: Deploy Project Artifacts to Vercel
        run: |
          cd output
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
